spring:
  application:
    name: paw-fund-backend
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/paw_fund
    username: root
    password: minhtranquang2197
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
  mail:
    host: smtp.gmail.com
    port: 587
    password: kqwb ipyc gkeh ligm
    username: brokenstar2197@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  version: v1.0.3
  access-token:
    secret-key: ftoLRVxHq82BzLq3stXhnOJRo4azrVab
    expired-duration: 4320
  refresh-token:
    expired-duration: 4320
  mail:
    username: brokenstar2197@gmail.com
    smtp:
      password: kqwb ipyc gkeh ligm
