spring:
  application:
    name: paw-fund-backend
  main:
    allow-circular-references: true
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/paw_fund}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:minhtranquang2197}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true

app:
  version: v1.0.0
  access-token:
    secret-key: ftoLRVxHq82BzLq3stXhnOJRo4azrVab
    expired-duration: 4320
  refresh-token:
    expired-duration: 4320
