spring:
  application:
    name: paw-fund-backend
  main:
    allow-circular-references: true
  datasource:
    url: ${DB_CONNECTION_STRING}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    password: ${MAIL_PASSWORD}
    username: ${MAIL_USERNAME}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  version: v1.0.3
  access-token:
    secret-key: ftoLRVxHq82BzLq3stXhnOJRo4azrVab
    expired-duration: 4320
  refresh-token:
    expired-duration: 4320
